name: Publish

env:
  DEBUG: napi:*
  APP_NAME: nestui

'on':
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - docs/**
  pull_request: null

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun" >> $GITHUB_PATH
      - name: Install dependencies
        run: bun install
      - name: Run tests
        run: bun run test
      - name: Publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          bun publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
